export interface ElementTransform {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
  zIndex: number;
}

export type IncentivesLayoutConfig = Record<string, ElementTransform>;

export const defaultTransform: ElementTransform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  zIndex: 10,
};

// AUTO-GENERATED BY VISUAL EDITOR
export const incentivesLayout: IncentivesLayoutConfig = {
  "certificate-image": {
    "x": 0,
    "y": 25,
    "scale": 1.5,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "certificate-label": {
    "x": 20,
    "y": 36,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "pass-image": {
    "x": 0,
    "y": 25,
    "scale": 2.25,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "pass-label": {
    "x": 5,
    "y": 36,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "merchandise-image": {
    "x": 0,
    "y": 25,
    "scale": 1.75,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "merchandise-label": {
    "x": 10,
    "y": 36,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "opportunities-image": {
    "x": 0,
    "y": 25,
    "scale": 2,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "opportunities-label": {
    "x": 25,
    "y": 36,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "pedestals": {
    "x": 0,
    "y": 61,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 0
  },
  "spotlight": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 5
  },
  "title": {
    "x": 0,
    "y": -50,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "text_recognition": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "text_experience": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "text_growth": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "text_legacy": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  }
};
