import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

export async function POST(req: Request) {
  // Security check: Only allow in development mode or if explicitly enabled
  if (process.env.NODE_ENV !== "development" && process.env.NEXT_PUBLIC_EDITOR_MODE !== "true") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  try {
    const layout = await req.json();

    const fileContent = `export interface ElementTransform {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
  zIndex: number;
}

export type IncentivesLayoutConfig = Record<string, ElementTransform>;

export const defaultTransform: ElementTransform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  zIndex: 10,
};

// AUTO-GENERATED BY VISUAL EDITOR
export const incentivesLayout: IncentivesLayoutConfig = ${JSON.stringify(layout, null, 2)};
`;

    const filePath = path.join(process.cwd(), "src", "config", "incentives-layout.ts");
    await fs.writeFile(filePath, fileContent, "utf8");

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Failed to save layout:", error);
    return NextResponse.json({ error: "Failed to save layout" }, { status: 500 });
  }
}
